services:
  mariadb:
    image: mariadb:11.4
    container_name: pop-storecomputer-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: pop_storecomputer
      MARIADB_USER: pop_user
      MARIADB_PASSWORD: pop_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
